### ISSUE TITLE
Hi, 你这个似乎有一些问题

### ISSUE THREAD

**Issue by archiewx** [Rynxiao/mint-ui-learn#1]
![2019-06-12 13 35 04](https://user-images.githubusercontent.com/22249411/59325850-28d01300-8d17-11e9-9c4a-4c0777dcc885.gif)

最后一个始终划不到哦

**Comment by Rynxiao** [comment]
@zsirfs 嗯，是的😁，先记下，有个时间改一下

**Comment by archiewx** [comment]
因为你列表多了一个原因。OK。感谢
